version: '1'
services:
   at:
    hostname: at-host
    build:
      context: ./
    volumes:
      - ./:/at
    environment:
      TEST_ENVIRONMENT: ${TEST_ENVIRONMENT}
      STAY_ALIVE: ${STAY_ALIVE}
